### ISSUE TITLE
Client IRC doit s'enregistrer pour join le channel

### ISSUE THREAD

**Issue by SabaLeonel** [42-Student-Teams/IRC#1]

**Comment by Arcadiastyx** [comment]
Un système d'authentifications a été mis en place. 

La fonction excInput , de la class Parser = Permet de gérer les permissions d’exécutions de commandes .

Comment ça fonctionne : 
→ le constructeur de la class Command est construit comme suit : Command::Command(Server* srv, bool auth) :_srv(srv), _auth(auth) {}
→ et il possède la fonction cmdPermission qui renvoie _auth = bool    Command::cmdPermission() const { return _auth; }
→ lors de la création d’une commande qui hérite de la class Command, cette dernière pourra être définie comme TRUE or FALSE
→ si TRUE alors = la commande nécessite une authentification pour être exécutée et empêchera l'utilisateur d’en faire usage 
→ si FALSE alors = le client et libre d’utilisé la commande
