### ISSUE TITLE
Gestion des messages dans les channels

### ISSUE THREAD

**Issue by SabaLeonel** [42-Student-Teams/IRC#3]
Ensure that all messages from one client on that channel are sent to all other clients that joined the channel.

**Comment by neilamumi** [comment]
- [x] les messages ne sont pas envoyé apres un join
- [x] une foie que les messages sont fonctionnels ajouter des tests de verifications voir https://dd.ircdocs.horse/refs/commands/join

**Comment by SabaLeonel** [comment]
Corrigé avec le dernier merge/push
