### ISSUE TITLE
Tester toutes les commandes IRC

### ISSUE THREAD

**Issue by SabaLeonel** [42-Student-Teams/IRC#5]
- [x] MODE
- [x] COMMANDE
- [x] JOIN
- [x] LIST
- [x] NICK
- [x] NOTICE
- [x] PARSER
- [x] PART
- [x] PRIVMSG
- [x] QUIT
- [x] USER
- [x] WHO

**Comment by neilamumi** [comment]
PRVMSG
- message privé ok
- message canal pas de test parce que le join a des soucis

à voir : est ce que privmsg peut etre tuilisé si on fait pas partie du canal, preference de la doc : non

**Comment by neilamumi** [comment]
PART 

- part un channel uniquement quand il commence par # ok
- part plusieurs channels pas possible ok
- part un channel qu'il a deja part denouveau message
