### ISSUE TITLE
 Avoir des operators et des utilisateurs basiques. Fonctionnel 

### ISSUE THREAD

**Issue by SabaLeonel** [42-Student-Teams/IRC#6]
Implémenter les commandes spécifiques aux opérateurs de
canaux.

1. KICK - Ejecter un client du channel
2. INVITE - Inviter un client au channel
3. TOPIC - Modifier ou afficher le thème du channel
4. MODE - Changer le mode du channel : 

- i : Définir/supprimer le canal sur invitation uniquement
- t : Définir/supprimer les restrictions de la commande TOPIC pour les opérateurs de canaux
- k : Définir/supprimer la clé du canal (mot de passe)
- o : Donner/retirer le privilège de l’opérateur de canal
- l : Définir/supprimer la limite d’utilisateurs pour le canal

**Comment by Arcadiastyx** [comment]
les cmds pour l operator sont fonctionnel, manque plus que KICK , Neila en charge
