### ISSUE TITLE
Adapter le Protocol entre Irssi et le Serveur

### ISSUE THREAD

**Issue by Arcadiastyx** [42-Student-Teams/IRC#8]
- [x]  Vérifier la fonction :  void Server::handleClientMessage(int fd), en charge du parsing des messages
- [x]  Débloqué, la condition : Si le client n'est pas enregistré, limité les commandes à NICK, PASS, USER et QUIT , fonctionnel sur 
 NC , mais bloqué par Irssi. ( car Irssi semble remplir par défaut les conditions d'enregistrement pour le serveur)
- [x]  Réglé le problème de connexion avec irssi : on est automatiquement déconnecté par Irssi et en plus, semble incrémenter le nombre d'user dans la map:: _clients.
- [x]  1. Comprendre pourquoi Irssi nous déconnecte
- [x]  2. Vérifier pourquoi le code garde en mémoire le client qui entre via Irssi et n'est pas delete de la liste

**Comment by SabaLeonel** [comment]
Se connecter avec le client irssi fonctionne. Il faut tester la commande PART car elle ne semble pas fonctionner sous irssi.
